{% set name = "mysql-connector-python" %}
{% set version = "8.3.0+sgl2" %}
{% set sha256 = "62d49948753f9be39aed7d6a3a61023962424dd36bae31029d25f0a1f2af8d73" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/willmmiles/mysql-connector-python/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    #- patches/0001-Typecast-password-to-const-char-explicitly-py3.patch
    # - patches/0002-Cast-uint-to-enum-mysql_enum_shutdown_level-explicit.patch
    - patches/0003-Fix-location-for-searching-mysql-headers-and-libs-on.patch
    - patches/0004-Fix-indentation-for-common-flags.patch
    #- patches/0005-Revert-Fix-MacOS-wheels-platform-tag.patch
    - patches/0006-Replace-google-protobuf-string-with-std-string.patch
    - patches/0007-Delete-openssl-vendor-ed-libs-only-if-provided.patch

build:
  number: 1
  # VS 2008 is not supported for libprotobuf
  skip: true  # [win and py2k]
  script: # [unix]
    - PROTOBUF_INCLUDE_DIR=$PREFIX/include PROTOBUF_LIB_DIR=$PREFIX/lib PROTOC=$BUILD_PREFIX/bin/protoc MYSQL_CAPI=$PREFIX pip install .\mysql-connector-python --no-deps --verbose # [unix]
    #- PROTOBUF_INCLUDE_DIR=$PREFIX/include PROTOBUF_LIB_DIR=$PREFIX/lib PROTOC=$BUILD_PREFIX/bin/protoc MYSQL_CAPI=$PREFIX pip install .\mysqlx-connector-python --no-deps --verbose # [unix]
  script: # [win]
    - set "PROTOBUF_INCLUDE_DIR=%LIBRARY_INC%"  # [win]
    - set "PROTOBUF_LIB_DIR=%LIBRARY_LIB%" # [win]
    - set "PROTOC=%LIBRARY_BIN%/protoc.exe" # [win]
    - set "MYSQL_CAPI=%LIBRARY_PREFIX%" # [win]
    - set "CL=/DPROTOBUF_USE_DLLS"  # [win]
    - set "SKIP_VENDOR=1"  # [win]    
    - pip install .\mysql-connector-python --no-deps --verbose # [win]
    #- pip install .\mysqlx-connector-python --no-deps --verbose # [win]


requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - libprotobuf

  host:
    - python
    - pip
    - mysql-devel >=8.0
    - libprotobuf
    - protobuf >=3.11.0,<=3.20.3
    - zlib

  run:
    - python
    - protobuf >=3.11.0,<=3.20.3
    - dnspython >=1.16.0

test:
  imports:
    - mysql
    - mysql.connector
    #- mysqlx
    #- mysqlx.protobuf


about:
  home: https://dev.mysql.com/doc/connector-python/en/
  license: GPL-2.0-or-later WITH Universal-FOSS-exception-1.0
  license_family: GPL
  license_file: LICENSE.txt
  summary: Python driver for communicating with MySQL servers

  description: |
    MySQL Connector/Python is a standardized database driver for Python
    platforms and development.
  doc_url: http://dev.mysql.com/doc/connector-python/en/index.html
  dev_url: https://github.com/mysql/mysql-connector-python

extra:
  recipe-maintainers:
    - synapticarbors
    - nehaljwani
