bot:
  check_solvable: true
build_platform:
  linux_aarch64: linux_64
  linux_ppc64le: linux_64
  osx_arm64: osx_64
conda_build:
  pkg_format: '2'
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
  user_or_org: willmmiles
provider:
  linux_aarch64: default
  win: azure
test_on_native_only: true
channels:
  targets:
    - ["wmiles_sgl", "main"]
azure:
  user_or_org: "wmiles-sgl"
